### ISSUE TITLE
Catalog and Hardware section not complete

### ISSUE THREAD

**Issue by olterion** [OpenKNX/Kaenx-Creator#53]
The Catalog and Hardware section are not complete.
If I import a knxprod with several different hardwares and catalog entries with translations, the export can not be imported by ETS.
Error from ETS: "Die Sequenz enthält kein übereinstimmendes Element"

To reproduce:
1. Import MDT binary input V20a with application "Binary input 4f" ([MDT_KP_Binaereingang_V20a.zip](https://github.com/user-attachments/files/16943009/MDT_KP_Binaereingang_V20a.zip))
2. Export this without any changes.
3. Import the exported knxprod with ETS.
4. Get Error from ETS

Now there is 3 times the same entry in catalog.xml, I think, there comes the error in ETS.

Connections between Hardware and Catalog items are not visible (which hardware belongs to which catalog entry)
Translations for Catalog entries are not editable.

**Comment by thewhobox** [comment]
The Creator is not designed for more than one hardware and knxprod.
Since there is only one hardware you dont need to configure it.

I added a fix so you can select which product should be importet, if there is mor than one product for this hardware.

Now i can import the created knxprod in ets without problems.
